# 主配置文件中需要从这里读取
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: nswddjjy333

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI4GKnjNcc6tFio2wzajJT
    access-key-secret: MLSWwllj1iK138I0CBzG1yyA7oQ9au
    bucket-name: treehole
    dir-path: backend-demo-skyout/